In [ ]:
import numpy as np
a = np.array([[0, 1],
             [2, 3],
             [4, 5]])

b = np.array([[0, 1, 2, 3],
             [4, 5, 6, 7]])

dot_array = np.dot(a, b)
print(dot_array)

print(dot_array.max())


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
